services:
    netgen_layouts.remote_media.browser.backend.remote_media_image:
        class: Netgen\Layouts\RemoteMedia\ContentBrowser\Backend\ImageBackend
        arguments:
            - "@netgen_remote_media.provider.cloudinary"
            - "@netgen_layouts.remote_media.helper.resource_id"
            - "@netgen_remote_media.next_cursor_resolver"
        tags:
            - { name: netgen_content_browser.backend, item_type: remote_media_image }

    netgen_layouts.remote_media.browser.column_value_provider.remote_media_image.tags:
        class: Netgen\Layouts\RemoteMedia\ContentBrowser\Item\ColumnProvider\Image\Tags
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: remote_media_image\tags }

    netgen_layouts.remote_media.browser.column_value_provider.remote_media_image.width:
        class: Netgen\Layouts\RemoteMedia\ContentBrowser\Item\ColumnProvider\Image\Width
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: remote_media_image\width }

    netgen_layouts.remote_media.browser.column_value_provider.remote_media_image.height:
        class: Netgen\Layouts\RemoteMedia\ContentBrowser\Item\ColumnProvider\Image\Height
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: remote_media_image\height }
