services:
    netgen_content_browser.backend.cloudinary_image:
        class: Netgen\Layouts\RemoteMedia\ContentBrowser\Backend\ImageBackend
        arguments:
            - "@netgen_remote_media.provider.cloudinary"
        tags:
            - { name: netgen_content_browser.backend, item_type: cloudinary_image }
