services:
    netgen_layouts.remote_media.item.value_converter.remote_media:
        class: Netgen\Layouts\RemoteMedia\Item\ValueConverter\RemoteMediaValueConverter
        tags:
            - { name: netgen_layouts.cms_value_converter }

    netgen_layouts.remote_media.item.value_loader.remote_media:
        class: Netgen\Layouts\RemoteMedia\Item\ValueLoader\RemoteMediaValueLoader
        arguments:
            - "@netgen_remote_media.provider.cloudinary"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: netgen_layouts.cms_value_loader, value_type: remote_media }

    netgen_layouts.remote_media.item.value_url_generator.remote_media:
        class: Netgen\Layouts\RemoteMedia\Item\ValueUrlGenerator\RemoteMediaValueUrlGenerator
        tags:
            - { name: netgen_layouts.cms_value_url_generator, value_type: remote_media }
