services:
    netgen_layouts.remote_media.templating.twig.extension.remote_media:
        class: Netgen\Bundle\LayoutsRemoteMediaBundle\Templating\Twig\Extension\RemoteMediaExtension
        tags:
            - { name: twig.extension }

    netgen_layouts.remote_media.templating.twig.runtime.remote_media:
        class: Netgen\Bundle\LayoutsRemoteMediaBundle\Templating\Twig\Runtime\RemoteMediaRuntime
        arguments:
            - "@netgen_remote_media.provider"
        tags:
            - { name: twig.runtime }
