view:
    item_view:
        app:
            remote_media_image:
                template: "@NetgenLayoutsRemoteMedia/app/item/view/remote_media_image.html.twig"
                match:
                    item\value_type: remote_media_image
