view:
    item_view:
        app:
            remote_media:
                template: "@NetgenLayoutsRemoteMedia/app/item/view/remote_media.html.twig"
                match:
                    item\value_type: remote_media
