parameters:
    netgen_layouts.remote_media.layouts_block.allowed_resource_types:
        - image
        - video
        - raw

    netgen_layouts.app.ezplatform.item_preview_template: '@@NetgenLayoutsRemoteMedia/app/item/nglayouts_app_preview.html.twig'
