orm:
    entity_managers:
        default:
            auto_mapping: false
            mappings:
                netgen_layouts.remote_media:
                    type: annotation
                    prefix: Netgen\Layouts\RemoteMedia\API\Values
                    dir: "%kernel.root_dir%/../vendor/netgen/layouts-remote-media/lib/API/Values"
                    is_bundle: false
