system:
    default:
        image_variations:
            default:
                nglayouts_app_preview:
                    transformations:
                        - { name: resize, params: [ 160, 90 ] }
                        - { name: quality, params: [ 'auto:low' ] }
            netgen_layouts_block:
                small:
                    transformations:
                        - { name: crop, params: [200, 200] }
                        - { name: resize, params: [200, 200] }
                medium:
                    transformations:
                        - { name: crop, params: [800, 450] }
                        - { name: resize, params: [800, 450] }
                large:
                    transformations:
                        - { name: crop, params: [1600, 900] }
                        - { name: resize, params: [1600, 900] }
