item_types:
    remote_media_image:
        name: item_types.remote_media_image
        preview:
            template: '@NetgenLayoutsRemoteMedia/ngcb/remote_media_image.html.twig'
        columns:
            name:
                name: columns.name
                value_provider: name
        default_columns:
            - name
